### ISSUE TITLE
Technical Document extraction - error message

### ISSUE THREAD

**Issue by jamesmarvel** [jwiesel/sfdcCommander#27]
Another issue we're encountering is when we extract the technical document.

this is the error message from command line
Writing results to zip file
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at de.sfdccommander.controller.MetadataRetriever.writeZip(MetadataRetrie
ver.java:158)
        at de.sfdccommander.controller.MetadataRetriever.retrieveZips(MetadataRe
triever.java:123)
        at de.sfdccommander.controller.MetadataExporter.getEntities(MetadataExpo
rter.java:65)
        at de.sfdccommander.controller.Tasks.render(Tasks.java:38)
        at de.sfdccommander.viewer.ConfigActionPanel$1.actionPerformed(ConfigAct
ionPanel.java:103)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Sour
ce)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

any idea as to what's going wrong here?

**Comment by jwiesel** [comment]
Hi @jamesmarvel,
first of all: Sorry for the late response. I didn't work on the project for some time.
This error-message occurs, if the application cannot write the zip-file. This might either be caused by missing permissions in the file-location or if the "System Name" contains illegal characters. The new version will check, if the system name is okay.

Until then, please check the following entries in your config-file. 

> sf.systemname
> target.systemname

They should not contain the following characters: ` '/', '\n', '\r', '\t', '\0', '\f', 'backtick', '?', '*', '\\', '<', '>', '|', '\"', ':' `
