### ISSUE TITLE
Metadata backup failing

### ISSUE THREAD

**Issue by anandghegde** [jwiesel/sfdcCommander#28]
I ran the metadata retrieval command and got this error - 

```
Starting sfdcCommander...
--------------------------------
Gathering Metadata from your Org...
Entity InstalledPackage contains 88 visible element(s).
Entity CustomLabels contains 1 visible element(s).
Entity StaticResource contains 853 visible element(s).
Entity Scontrol contains 147 visible element(s).
Entity AuraDefinitionBundle contains 4 visible element(s).
Entity ApexComponent contains 329 visible element(s).
Entity ApexPage contains 1992 visible element(s).
Entity Queue contains 400 visible element(s).
Entity Role contains 2482 visible element(s).
Entity Group contains 283 visible element(s).
Entity CustomObject contains 1575 visible element(s).
Entity ReportType contains 298 visible element(s).
Entity AnalyticSnapshot contains 3 visible element(s).
Entity Layout contains 1628 visible element(s).
Entity CustomPageWebLink contains 77 visible element(s).
Entity Letterhead contains 12 visible element(s).
Entity QuickAction contains 49 visible element(s).
Entity FlexiPage contains 1 visible element(s).
Entity CustomTab contains 575 visible element(s).
Entity CustomApplicationComponent contains 4 visible element(s).
Entity CustomApplication contains 74 visible element(s).
Entity Portal contains 2 visible element(s).
Entity Flow contains 20 visible element(s).
Entity FlowDefinition contains 7 visible element(s).
Entity Workflow contains 1563 visible element(s).
Entity AssignmentRules contains 2 visible element(s).
Entity AutoResponseRules contains 2 visible element(s).
Entity EscalationRules contains 1 visible element(s).
Entity ApprovalProcess contains 179 visible element(s).
Entity HomePageComponent contains 48 visible element(s).
Entity HomePageLayout contains 11 visible element(s).
Entity CustomObjectTranslation contains 3347 visible element(s).
Entity Translations contains 1 visible element(s).
Entity ApexClass contains 7497 visible element(s).
Entity ApexTrigger contains 704 visible element(s).
Entity Profile contains 137 visible element(s).
Entity PermissionSet contains 352 visible element(s).
Entity CustomMetadata contains 123 visible element(s).
Entity DataCategoryGroup contains 5 visible element(s).
Entity RemoteSiteSetting contains 43 visible element(s).
Entity MatchingRules contains 3 visible element(s).
Entity CustomSite contains 4 visible element(s).
Entity SharingRules contains 1019 visible element(s).
Entity Community contains 5 visible element(s).
Entity CallCenter contains 3 visible element(s).
Entity MilestoneType contains 10 visible element(s).
Entity EntitlementProcess contains 115 visible element(s).
Entity ConnectedApp contains 8 visible element(s).
Entity AppMenu contains 2 visible element(s).
Entity SiteDotCom contains 2 visible element(s).
Entity Network contains 2 visible element(s).
Entity ManagedTopics contains 2 visible element(s).
Entity SamlSsoConfig contains 3 visible element(s).
Entity Settings contains 20 visible element(s).
4 meta-data package(s) defined to be downloaded.
--------------------------------
Downloading metadata package #1
Retrieve Status: InProgress
Retrieve Status: InProgress
Retrieve Status: InProgress
Retrieve Status: InProgress
Retrieve Status: InProgress
Retrieve Status: InProgress
Retrieve Status: InProgress
Error: Could not download zip-File from your Org.

```

I suspect this is because each package contains more than 10k files? ( I dont know what the limit is)

**Comment by anandghegde** [comment]
This is still happening even with the latest release.

**Comment by jwiesel** [comment]
Hi @anandghegde,
I just checked the source-code. The shown error message can be caused by different reasons. My gut-feeling: The salesforce-api sends an error code during retrieval. This code is only logged, but not shown right now. Can you please provide the stack-trace from your log-file under:?

> log/commander.log

**Comment by anandghegde** [comment]
Here is the commander.log output
```

2017-02-10 16:17:00,998 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Application started.
2017-02-10 16:17:01,003 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Starting sfdcCommander...
2017-02-10 16:18:44,579 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Application started.
2017-02-10 16:18:44,586 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Starting sfdcCommander...
2017-02-10 16:19:45,829 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Application started.
2017-02-10 16:19:45,836 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Starting sfdcCommander...
2017-02-10 16:21:20,751 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Application started.
2017-02-10 16:21:20,758 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Starting sfdcCommander...
2017-02-10 16:22:41,149 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Application started.
2017-02-10 16:22:41,156 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Starting sfdcCommander...
2017-02-10 16:22:41,373 [main] WARN  org.apache.axis.utils.JavaUtils  - Unable to find required classes (javax.activation.DataHandler and javax.mail.internet.MimeMultipart). Attachment support is disabled.
2017-02-10 16:22:44,132 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - --------------------------------
2017-02-10 16:22:44,132 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Gathering Metadata from your Org...
2017-02-10 16:22:48,852 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity InstalledPackage contains 92 visible element(s).
2017-02-10 16:22:49,947 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomLabels contains 1 visible element(s).
2017-02-10 16:22:56,801 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity StaticResource contains 886 visible element(s).
2017-02-10 16:22:59,002 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Scontrol contains 147 visible element(s).
2017-02-10 16:23:00,126 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity AuraDefinitionBundle contains 4 visible element(s).
2017-02-10 16:23:04,838 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ApexComponent contains 335 visible element(s).
2017-02-10 16:23:14,597 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ApexPage contains 2044 visible element(s).
2017-02-10 16:23:19,011 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Queue contains 419 visible element(s).
2017-02-10 16:23:31,917 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Role contains 2523 visible element(s).
2017-02-10 16:23:35,447 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Group contains 288 visible element(s).
2017-02-10 16:23:45,696 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomObject contains 1668 visible element(s).
2017-02-10 16:23:50,484 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ReportType contains 321 visible element(s).
2017-02-10 16:23:54,631 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity AnalyticSnapshot contains 3 visible element(s).
2017-02-10 16:24:03,559 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Layout contains 1718 visible element(s).
2017-02-10 16:24:06,745 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomPageWebLink contains 77 visible element(s).
2017-02-10 16:24:08,126 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Letterhead contains 12 visible element(s).
2017-02-10 16:24:10,907 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity QuickAction contains 49 visible element(s).
2017-02-10 16:24:17,372 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomTab contains 600 visible element(s).
2017-02-10 16:24:18,569 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomApplicationComponent contains 4 visible element(s).
2017-02-10 16:24:20,548 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomApplication contains 76 visible element(s).
2017-02-10 16:24:21,635 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Portal contains 2 visible element(s).
2017-02-10 16:24:23,977 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Flow contains 20 visible element(s).
2017-02-10 16:24:25,338 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity FlowDefinition contains 7 visible element(s).
2017-02-10 16:24:36,727 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Workflow contains 1656 visible element(s).
2017-02-10 16:24:37,759 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity AssignmentRules contains 2 visible element(s).
2017-02-10 16:24:38,838 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity AutoResponseRules contains 2 visible element(s).
2017-02-10 16:24:39,941 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity EscalationRules contains 1 visible element(s).
2017-02-10 16:24:45,032 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ApprovalProcess contains 188 visible element(s).
2017-02-10 16:24:46,373 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity HomePageComponent contains 47 visible element(s).
2017-02-10 16:24:47,671 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity HomePageLayout contains 11 visible element(s).
2017-02-10 16:25:03,041 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomObjectTranslation contains 3451 visible element(s).
2017-02-10 16:25:04,774 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Translations contains 1 visible element(s).
2017-02-10 16:25:47,053 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ApexClass contains 7796 visible element(s).
2017-02-10 16:25:53,439 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ApexTrigger contains 738 visible element(s).
2017-02-10 16:25:55,915 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Profile contains 140 visible element(s).
2017-02-10 16:26:00,631 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity PermissionSet contains 362 visible element(s).
2017-02-10 16:26:05,444 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomMetadata contains 307 visible element(s).
2017-02-10 16:26:06,612 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity DataCategoryGroup contains 5 visible element(s).
2017-02-10 16:26:07,991 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity RemoteSiteSetting contains 45 visible element(s).
2017-02-10 16:26:09,102 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity MatchingRules contains 3 visible element(s).
2017-02-10 16:26:11,353 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomSite contains 4 visible element(s).
2017-02-10 16:26:21,830 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity SharingRules contains 1074 visible element(s).
2017-02-10 16:26:23,941 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Community contains 5 visible element(s).
2017-02-10 16:26:25,016 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CallCenter contains 3 visible element(s).
2017-02-10 16:26:26,404 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity MilestoneType contains 10 visible element(s).
2017-02-10 16:26:27,712 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity EntitlementProcess contains 117 visible element(s).
2017-02-10 16:26:30,250 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ConnectedApp contains 9 visible element(s).
2017-02-10 16:26:31,288 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity AppMenu contains 2 visible element(s).
2017-02-10 16:26:32,400 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity SiteDotCom contains 2 visible element(s).
2017-02-10 16:26:33,498 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Network contains 2 visible element(s).
2017-02-10 16:26:34,670 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ManagedTopics contains 2 visible element(s).
2017-02-10 16:26:35,757 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity SamlSsoConfig contains 2 visible element(s).
2017-02-10 16:26:42,562 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Settings contains 20 visible element(s).
2017-02-10 16:26:42,562 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - 4 meta-data package(s) defined to be downloaded.
2017-02-10 16:26:42,562 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - --------------------------------
2017-02-10 16:26:42,562 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Downloading metadata package #1
2017-02-10 16:26:47,414 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Retrieve Status: InProgress
2017-02-10 16:26:50,478 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Retrieve Status: InProgress
2017-02-10 16:26:56,449 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Retrieve Status: InProgress
2017-02-10 16:27:05,487 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Retrieve Status: InProgress
2017-02-10 16:27:22,695 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Retrieve Status: InProgress
2017-02-10 16:27:56,335 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Retrieve Status: InProgress
2017-02-10 16:29:02,304 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Retrieve Status: InProgress
2017-02-10 16:54:23,901 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Application started.
2017-02-10 16:54:23,905 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Starting sfdcCommander...
2017-02-10 16:54:24,024 [main] WARN  org.apache.axis.utils.JavaUtils  - Unable to find required classes (javax.activation.DataHandler and javax.mail.internet.MimeMultipart). Attachment support is disabled.
2017-02-10 16:54:26,087 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - --------------------------------
2017-02-10 16:54:26,087 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Gathering Metadata from your Org...
2017-02-10 16:54:30,835 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity InstalledPackage contains 92 visible element(s).
2017-02-10 16:54:31,991 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomLabels contains 1 visible element(s).
2017-02-10 16:54:38,397 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity StaticResource contains 886 visible element(s).
2017-02-10 16:54:40,622 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Scontrol contains 147 visible element(s).
2017-02-10 16:54:41,690 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity AuraDefinitionBundle contains 4 visible element(s).
2017-02-10 16:54:46,079 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ApexComponent contains 335 visible element(s).
2017-02-10 16:54:55,314 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ApexPage contains 2044 visible element(s).
2017-02-10 16:54:59,368 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Queue contains 419 visible element(s).
2017-02-10 16:55:12,387 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Role contains 2523 visible element(s).
2017-02-10 16:55:16,073 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Group contains 288 visible element(s).
2017-02-10 16:55:25,720 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomObject contains 1668 visible element(s).
2017-02-10 16:55:30,253 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ReportType contains 321 visible element(s).
2017-02-10 16:55:34,220 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity AnalyticSnapshot contains 3 visible element(s).
2017-02-10 16:55:46,892 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Layout contains 1718 visible element(s).
2017-02-10 16:55:49,914 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomPageWebLink contains 77 visible element(s).
2017-02-10 16:55:51,306 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Letterhead contains 12 visible element(s).
2017-02-10 16:55:55,972 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity QuickAction contains 49 visible element(s).
2017-02-10 16:56:02,190 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomTab contains 600 visible element(s).
2017-02-10 16:56:04,221 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomApplicationComponent contains 4 visible element(s).
2017-02-10 16:56:06,088 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomApplication contains 76 visible element(s).
2017-02-10 16:56:07,173 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Portal contains 2 visible element(s).
2017-02-10 16:56:08,826 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Flow contains 20 visible element(s).
2017-02-10 16:56:10,102 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity FlowDefinition contains 7 visible element(s).
2017-02-10 16:56:21,209 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Workflow contains 1656 visible element(s).
2017-02-10 16:56:22,344 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity AssignmentRules contains 2 visible element(s).
2017-02-10 16:56:23,422 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity AutoResponseRules contains 2 visible element(s).
2017-02-10 16:56:24,474 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity EscalationRules contains 1 visible element(s).
2017-02-10 16:56:28,113 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ApprovalProcess contains 188 visible element(s).
2017-02-10 16:56:29,755 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity HomePageComponent contains 47 visible element(s).
2017-02-10 16:56:30,889 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity HomePageLayout contains 11 visible element(s).
2017-02-10 16:56:48,042 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomObjectTranslation contains 3451 visible element(s).
2017-02-10 16:56:50,460 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Translations contains 1 visible element(s).
2017-02-10 16:57:17,217 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ApexClass contains 7796 visible element(s).
2017-02-10 16:57:23,721 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ApexTrigger contains 738 visible element(s).
2017-02-10 16:57:26,332 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Profile contains 140 visible element(s).
2017-02-10 16:57:30,575 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity PermissionSet contains 362 visible element(s).
2017-02-10 16:57:34,434 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomMetadata contains 307 visible element(s).
2017-02-10 16:57:35,596 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity DataCategoryGroup contains 5 visible element(s).
2017-02-10 16:57:36,922 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity RemoteSiteSetting contains 45 visible element(s).
2017-02-10 16:57:38,111 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity MatchingRules contains 3 visible element(s).
2017-02-10 16:57:40,305 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CustomSite contains 4 visible element(s).
2017-02-10 16:57:49,154 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity SharingRules contains 1074 visible element(s).
2017-02-10 16:57:50,362 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Community contains 5 visible element(s).
2017-02-10 16:57:51,471 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity CallCenter contains 3 visible element(s).
2017-02-10 16:57:53,039 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity MilestoneType contains 10 visible element(s).
2017-02-10 16:57:54,784 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity EntitlementProcess contains 117 visible element(s).
2017-02-10 16:57:57,838 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ConnectedApp contains 9 visible element(s).
2017-02-10 16:57:58,887 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity AppMenu contains 2 visible element(s).
2017-02-10 16:57:59,978 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity SiteDotCom contains 2 visible element(s).
2017-02-10 16:58:01,015 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Network contains 2 visible element(s).
2017-02-10 16:58:02,056 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity ManagedTopics contains 2 visible element(s).
2017-02-10 16:58:03,070 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity SamlSsoConfig contains 2 visible element(s).
2017-02-10 16:58:09,747 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Entity Settings contains 20 visible element(s).
2017-02-10 16:58:09,747 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - 4 meta-data package(s) defined to be downloaded.
2017-02-10 16:58:09,747 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - --------------------------------
2017-02-10 16:58:09,747 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Downloading metadata package #1
2017-02-10 16:58:14,597 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Retrieve Status: Pending
2017-02-10 16:58:17,661 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Retrieve Status: Pending
2017-02-10 16:58:22,754 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Retrieve Status: InProgress
2017-02-10 16:58:32,739 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Retrieve Status: InProgress
2017-02-10 16:58:49,828 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Retrieve Status: InProgress
2017-02-10 16:59:23,443 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Retrieve Status: InProgress
2017-02-10 17:00:28,810 [main] INFO  de.sfdccommander.viewer.SfdcCommander  - Retrieve Status: InProgress
2017-02-10 17:12:51,804 [main] ERROR de.sfdccommander.viewer.SfdcCommander  - Could not download zip-File from your Org.
de.sfdccommander.controller.helper.CommanderException: Could not download zip-File from your Org.
	at de.sfdccommander.controller.MetadataExporter.getEntities(MetadataExporter.java:83)
	at de.sfdccommander.controller.Tasks.exportSrc(Tasks.java:28)
	at de.sfdccommander.controller.StartModeDispatcher.dispatch(StartModeDispatcher.java:89)
	at de.sfdccommander.viewer.SfdcCommander.<init>(SfdcCommander.java:56)
	at de.sfdccommander.viewer.SfdcCommander.getInstance(SfdcCommander.java:34)
	at de.sfdccommander.viewer.SfdcCommander.main(SfdcCommander.java:25)
Caused by: de.sfdccommander.controller.helper.CommanderException: Could not retrieve metadata.
	at de.sfdccommander.controller.MetadataRetriever.retrieveZips(MetadataRetriever.java:127)
	at de.sfdccommander.controller.MetadataExporter.getEntities(MetadataExporter.java:65)
	... 5 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 144581322; XML document structures must start and end within the same entity.
	at org.apache.axis.AxisFault.makeFault(AxisFault.java:101)
	at org.apache.axis.SOAPPart.getAsSOAPEnvelope(SOAPPart.java:701)
	at org.apache.axis.Message.getSOAPEnvelope(Message.java:435)
	at org.apache.axis.handlers.soap.MustUnderstandChecker.invoke(MustUnderstandChecker.java:62)
	at org.apache.axis.client.AxisClient.invoke(AxisClient.java:206)
	at org.apache.axis.client.Call.invokeEngine(Call.java:2784)
	at org.apache.axis.client.Call.invoke(Call.java:2767)
	at org.apache.axis.client.Call.invoke(Call.java:2443)
	at org.apache.axis.client.Call.invoke(Call.java:2366)
	at org.apache.axis.client.Call.invoke(Call.java:1812)
	at com.sforce.soap._2006._04.metadata.MetadataBindingStub.checkRetrieveStatus(MetadataBindingStub.java:5347)
	at de.sfdccommander.controller.MetadataRetriever.retrieveZips(MetadataRetriever.java:99)
	... 6 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 144581322; XML document structures must start and end within the same entity.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.endEntity(XMLDocumentFragmentScannerImpl.java:898)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.endEntity(XMLDocumentScannerImpl.java:563)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.endEntity(XMLEntityManager.java:1399)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.load(XMLEntityScanner.java:1917)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityScanner.peekChar(XMLEntityScanner.java:507)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2713)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at org.apache.axis.encoding.DeserializationContext.parse(DeserializationContext.java:227)
	at org.apache.axis.SOAPPart.getAsSOAPEnvelope(SOAPPart.java:696)
	... 16 more
```
